### ISSUE TITLE
Hosting Bot HELP

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#107]
Hi, so I have a problem with Heroku when hosting Reaper2.0 here is the log

`C:\Users\natha\Desktop\N-Bot>heroku logs -a nate-bot-0
2021-11-08T20:40:45.886956+00:00 app[web.1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-08T20:40:45.886956+00:00 app[web.1]: at Module.require (node:internal/modules/cjs/loader:999:19)
2021-11-08T20:40:45.886957+00:00 app[web.1]: at require (node:internal/modules/cjs/helpers:102:18)
2021-11-08T20:40:45.886957+00:00 app[web.1]: at bindings (/app/node_modules/bindings/bindings.js:112:48)
2021-11-08T20:40:45.886958+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/better-sqlite3/lib/database.js:9:24)
2021-11-08T20:40:45.886958+00:00 app[web.1]: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2021-11-08T20:40:45.886958+00:00 app[web.1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
2021-11-08T20:40:45.886958+00:00 app[web.1]: at Module.load (node:internal/modules/cjs/loader:975:32) {
2021-11-08T20:40:45.886959+00:00 app[web.1]: code: 'ERR_DLOPEN_FAILED'
2021-11-08T20:40:45.886959+00:00 app[web.1]: }
2021-11-08T20:40:45.886963+00:00 app[web.1]:
2021-11-08T20:40:45.886964+00:00 app[web.1]: Node.js v17.0.1
2021-11-08T20:40:46.005262+00:00 heroku[web.1]: Process exited with status 1
2021-11-08T20:40:51.973050+00:00 heroku[worker.1]: Starting process with command `node index`
2021-11-08T20:40:52.765727+00:00 heroku[worker.1]: State changed from starting to up
2021-11-08T20:40:53.513708+00:00 app[worker.1]: /app/node_modules/bindings/bindings.js:121
2021-11-08T20:40:53.513717+00:00 app[worker.1]: throw e;
2021-11-08T20:40:53.513718+00:00 app[worker.1]: ^
2021-11-08T20:40:53.513718+00:00 app[worker.1]:
2021-11-08T20:40:53.513718+00:00 app[worker.1]: Error: The module '/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
2021-11-08T20:40:53.513719+00:00 app[worker.1]: was compiled against a different Node.js version using
2021-11-08T20:40:53.513719+00:00 app[worker.1]: NODE_MODULE_VERSION 93. This version of Node.js requires
2021-11-08T20:40:53.513720+00:00 app[worker.1]: NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
2021-11-08T20:40:53.513720+00:00 app[worker.1]: the module (for instance, using `npm rebuild` or `npm install`).
2021-11-08T20:40:53.513720+00:00 app[worker.1]: at Object.Module._extensions..node (node:internal/modules/cjs/loader:1177:18)
2021-11-08T20:40:53.513720+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32)
2021-11-08T20:40:53.513721+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-08T20:40:53.513721+00:00 app[worker.1]: at Module.require (node:internal/modules/cjs/loader:999:19)
2021-11-08T20:40:53.513721+00:00 app[worker.1]: at require (node:internal/modules/cjs/helpers:102:18)
2021-11-08T20:40:53.513721+00:00 app[worker.1]: at bindings (/app/node_modules/bindings/bindings.js:112:48)
2021-11-08T20:40:53.513722+00:00 app[worker.1]: at Object.<anonymous> (/app/node_modules/better-sqlite3/lib/database.js:9:24)
2021-11-08T20:40:53.513722+00:00 app[worker.1]: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2021-11-08T20:40:53.513722+00:00 app[worker.1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
2021-11-08T20:40:53.513722+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32) {
2021-11-08T20:40:53.513722+00:00 app[worker.1]: code: 'ERR_DLOPEN_FAILED'
2021-11-08T20:40:53.513722+00:00 app[worker.1]: }
2021-11-08T20:40:53.513728+00:00 app[worker.1]:
2021-11-08T20:40:53.513728+00:00 app[worker.1]: Node.js v17.0.1
2021-11-08T20:40:53.648373+00:00 heroku[worker.1]: Process exited with status 1
2021-11-08T20:40:53.720821+00:00 heroku[worker.1]: State changed from up to crashed
2021-11-08T20:40:53.736494+00:00 heroku[worker.1]: State changed from crashed to starting
2021-11-08T20:41:03.925365+00:00 heroku[worker.1]: Starting process with command `node index`
2021-11-08T20:41:04.861015+00:00 heroku[worker.1]: State changed from starting to up
2021-11-08T20:41:06.214042+00:00 app[worker.1]: /app/node_modules/bindings/bindings.js:121
2021-11-08T20:41:06.214053+00:00 app[worker.1]: throw e;
2021-11-08T20:41:06.214054+00:00 app[worker.1]: ^
2021-11-08T20:41:06.214054+00:00 app[worker.1]:
2021-11-08T20:41:06.214054+00:00 app[worker.1]: Error: The module '/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
2021-11-08T20:41:06.214055+00:00 app[worker.1]: was compiled against a different Node.js version using
2021-11-08T20:41:06.214055+00:00 app[worker.1]: NODE_MODULE_VERSION 93. This version of Node.js requires
2021-11-08T20:41:06.214055+00:00 app[worker.1]: NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
2021-11-08T20:41:06.214056+00:00 app[worker.1]: the module (for instance, using `npm rebuild` or `npm install`).
2021-11-08T20:41:06.214056+00:00 app[worker.1]: at Object.Module._extensions..node (node:internal/modules/cjs/loader:1177:18)
2021-11-08T20:41:06.214058+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32)
2021-11-08T20:41:06.214058+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-08T20:41:06.214059+00:00 app[worker.1]: at Module.require (node:internal/modules/cjs/loader:999:19)
2021-11-08T20:41:06.214059+00:00 app[worker.1]: at require (node:internal/modules/cjs/helpers:102:18)
2021-11-08T20:41:06.214059+00:00 app[worker.1]: at bindings (/app/node_modules/bindings/bindings.js:112:48)
2021-11-08T20:41:06.214059+00:00 app[worker.1]: at Object.<anonymous> (/app/node_modules/better-sqlite3/lib/database.js:9:24)
2021-11-08T20:41:06.214060+00:00 app[worker.1]: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2021-11-08T20:41:06.214060+00:00 app[worker.1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
2021-11-08T20:41:06.214060+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32) {
2021-11-08T20:41:06.214061+00:00 app[worker.1]: code: 'ERR_DLOPEN_FAILED'
2021-11-08T20:41:06.214061+00:00 app[worker.1]: }
2021-11-08T20:41:06.214066+00:00 app[worker.1]:
2021-11-08T20:41:06.214066+00:00 app[worker.1]: Node.js v17.0.1
2021-11-08T20:41:06.365987+00:00 heroku[worker.1]: Process exited with status 1
2021-11-08T20:41:06.788963+00:00 heroku[worker.1]: State changed from up to crashed
2021-11-08T20:43:56.000000+00:00 app[api]: Build started by user nathankamineni@gmail.com
2021-11-08T20:45:01.061426+00:00 app[api]: Deploy 3f9645ca by user nathankamineni@gmail.com
2021-11-08T20:45:01.061426+00:00 app[api]: Release v4 created by user nathankamineni@gmail.com
2021-11-08T20:45:01.306952+00:00 heroku[worker.1]: State changed from crashed to starting
2021-11-08T20:45:10.101093+00:00 heroku[worker.1]: Starting process with command `node index`
2021-11-08T20:45:10.798616+00:00 heroku[worker.1]: State changed from starting to up
2021-11-08T20:45:11.618588+00:00 app[worker.1]: /app/node_modules/bindings/bindings.js:121
2021-11-08T20:45:11.618599+00:00 app[worker.1]: throw e;
2021-11-08T20:45:11.618600+00:00 app[worker.1]: ^
2021-11-08T20:45:11.618600+00:00 app[worker.1]:
2021-11-08T20:45:11.618600+00:00 app[worker.1]: Error: The module '/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
2021-11-08T20:45:11.618601+00:00 app[worker.1]: was compiled against a different Node.js version using
2021-11-08T20:45:11.618601+00:00 app[worker.1]: NODE_MODULE_VERSION 93. This version of Node.js requires
2021-11-08T20:45:11.618602+00:00 app[worker.1]: NODE_MODULE_VERSION 102. Please try re-compiling or re-installing
2021-11-08T20:45:11.618602+00:00 app[worker.1]: the module (for instance, using `npm rebuild` or `npm install`).
2021-11-08T20:45:11.618602+00:00 app[worker.1]: at Object.Module._extensions..node (node:internal/modules/cjs/loader:1177:18)
2021-11-08T20:45:11.618603+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32)
2021-11-08T20:45:11.618603+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-08T20:45:11.618603+00:00 app[worker.1]: at Module.require (node:internal/modules/cjs/loader:999:19)
2021-11-08T20:45:11.618604+00:00 app[worker.1]: at require (node:internal/modules/cjs/helpers:102:18)
2021-11-08T20:45:11.618604+00:00 app[worker.1]: at bindings (/app/node_modules/bindings/bindings.js:112:48)
2021-11-08T20:45:11.618604+00:00 app[worker.1]: at Object.<anonymous> (/app/node_modules/better-sqlite3/lib/database.js:9:24)
2021-11-08T20:45:11.618605+00:00 app[worker.1]: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2021-11-08T20:45:11.618605+00:00 app[worker.1]: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
2021-11-08T20:45:11.618605+00:00 app[worker.1]: at Module.load (node:internal/modules/cjs/loader:975:32) {
2021-11-08T20:45:11.618605+00:00 app[worker.1]: code: 'ERR_DLOPEN_FAILED'
2021-11-08T20:45:11.618606+00:00 app[worker.1]: }
2021-11-08T20:45:11.618606+00:00 app[worker.1]:
2021-11-08T20:45:11.618606+00:00 app[worker.1]: Node.js v17.0.1
2021-11-08T20:45:11.762412+00:00 heroku[worker.1]: Process exited with status 1
2021-11-08T20:45:11.811457+00:00 heroku[worker.1]: State changed from up to crashed
2021-11-08T20:45:19.000000+00:00 app[api]: Build succeeded`

**Comment by Natesplanet** [comment]
Can anyone recommend a good place to host my bot?

**Comment by 1stminhcar** [comment]
replit.com

> 
> 
> Can anyone recommend a good place to host my bot?


[replit](replit.com)

**Comment by Natesplanet** [comment]
Tried that already has alot of errors 😕

**Comment by Simpleboy353** [comment]
Go to your `package.json` file and edit node version to "^16.10.0"

**Comment by Natesplanet** [comment]
![image](https://user-images.githubusercontent.com/92893096/140942312-57306c7a-c818-472f-b0ed-417538f66c4c.png)
Like this?

**Comment by Simpleboy353** [comment]
remove ">="

**Comment by Natesplanet** [comment]
on node correct?

**Comment by Natesplanet** [comment]
Also do I remove ">=" on npm too?

**Comment by Simpleboy353** [comment]
no that's okay

**Comment by Natesplanet** [comment]
ok

**Comment by Natesplanet** [comment]
It won't work still and then I tried bash and that did not work either (Btw I am using Heroku CLI)

![image](https://user-images.githubusercontent.com/92893096/140944828-b66a41d3-3a74-4f95-8760-5788b94a69b7.png)

**Comment by Simpleboy353** [comment]
can you try `npm rebuild better-sqlite3 --update-binary`

**Comment by Natesplanet** [comment]
Oh no now the commands wont work agh

**Comment by Simpleboy353** [comment]
error?

**Comment by Natesplanet** [comment]
And it crashed

**Comment by Natesplanet** [comment]
Its not live anymore

**Comment by Natesplanet** [comment]
Lemme check log

**Comment by Natesplanet** [comment]
![image](https://user-images.githubusercontent.com/92893096/140946724-b3e337c7-a28f-4be3-a2d1-926a33427442.png)

It worked at first when starting and then had some error

**Comment by Simpleboy353** [comment]
You need to change the process type from web to worker

**Comment by Natesplanet** [comment]
Yeah I was thinking about that too lemme check the worker 1 sec my wifi Is garbage 🗑️

**Comment by Natesplanet** [comment]
It works now :) for real xD
