### ISSUE TITLE
Replit Hosting Issue 😞 

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#118]
` node index
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/N-Bot/node_modules/discord.js/src/index.js
- /home/runner/N-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/N-Bot/node_modules/discord.js/src/index.js',
    '/home/runner/N-Bot/index.js'
  ]
}`

Can anyone please help?

**Comment by Natesplanet** [comment]
I just noticed that there were no node_modules but it won't download cuz I get errors when I do npm install!

**Comment by 1KxDipsy** [comment]
bro 
1st : You will copy the github link of reaper . [https://github.com/Simpleboy353/REAPER-2.0.git]
2nd : You will go to the replit [https://replit.com/repls] and you create a projet by clicing [+ Create Repl] then you click import from github & past the link of Reaper. wait a moment ... the replit system will detect the language of Reaper automatically if it tell you to choise langage chose node.js & click start.(dont run the project)
3nd : Until Now dont run the bot, you have the project : you will go to change this file config.json (enter the bot token , prefix , mongodb ... ) 
4nd : After that you will visit this link [https://discord.com/developers/applications] you choise your bot and you need to enable this intents like in the pic bellow .
5nd : Now you need to update node to 16 version : Use this code in Shell (if you dont know where this Shell lock bellow in the second pic) just copy  paste it & enter , wait for the finish :

```npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH```

6nd : Now you need to update discord js So use this command in Shell too & wait for the finish :

```npm install discord.js@latest```

7nd : Use this command to install all packages : ```npm install```

Last step : Use this command to run the bot : ```node .``` or Click  Run (Green Button).

N.B: For Config.json 

- To get the `ALEXFLIPNOTE_API_KEY`, join **AlexFlipNote's Discord Server** [https://discord.gg/mSPFqeMnJj]
- Watch this video [https://youtu.be/BPqJIl34gm8] to know, how to get the `YT_COOKIE`
- You may use any channel id for `ERROR_LOGS_CHANNEL`, but the bot **must be present** in the server you are choosing the ID - from.
- All **the errors your bot faces**, will be logged in the **ERROR_LOGS_CHANNEL**
- The **mongoPass must be a url**
- Visit Official MongoDB Website [https://mongodb.com/] to get **your mongoPass**


These steps is my own experience with Reaper Bot if you do this steps it should work with you & If you still have any error just share it with us here in this server : https://discord.com/invite/HrdCqWbYRr 
or leave me a message here 1KxDIPSY#0001 ofc if i can help ( Im not at home rn ).

![test10](https://user-images.githubusercontent.com/94085828/141389052-c3e12047-0b90-43a4-a61e-9210c4786cc5.PNG)
![test9](https://user-images.githubusercontent.com/94085828/141389053-8a5fe132-7af0-4a1d-a397-a4d0851cc976.PNG)

**Comment by Natesplanet** [comment]
Ty but wait keep the issue open. Just incase I have anymore errors cuz I am sleeping rn and I am not at my computer to do this!

**Comment by Natesplanet** [comment]
It still does not work :(

**Comment by Natesplanet** [comment]
![image](https://user-images.githubusercontent.com/92893096/141527034-08b19f2c-a809-42d8-ad7b-891c0c496424.png)

😞  Still the same error

**Comment by 1KxDipsy** [comment]
invite me to project

**Comment by Simpleboy353** [comment]
> ![image](https://user-images.githubusercontent.com/92893096/141527034-08b19f2c-a809-42d8-ad7b-891c0c496424.png)
> 
> 😞 Still the same error

reinstall discord.js

**Comment by Natesplanet** [comment]
> invite me to project

I will dm u on discord

**Comment by Natesplanet** [comment]
Still doesn't work! 😞 


` node index
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/N-Bot/node_modules/discord.js/src/index.js
- /home/runner/N-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/N-Bot/node_modules/discord.js/src/index.js',
    '/home/runner/N-Bot/index.js'
  ]
}
 ^C
 node index
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/N-Bot/node_modules/discord.js/src/index.js
- /home/runner/N-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/N-Bot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/N-Bot/node_modules/discord.js/src/index.js',
    '/home/runner/N-Bot/index.js'
  ]
}`

**Comment by Natesplanet** [comment]
It works now.
I had to make a new replit and do all of this

https://github.com/Simpleboy353/REAPER-2.0/issues/118#issuecomment-966728880
