### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by finley541** [Simpleboy353/REAPER-2.0#135]
When I use node . I get this error:

QiMac:REAPER-2.0 quinns$ node .
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/quinns/REAPER-2.0/node_modules/chalk/source/index.js
require() of ES modules is not supported.
require() of /Users/quinns/REAPER-2.0/node_modules/chalk/source/index.js from /Users/quinns/REAPER-2.0/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/quinns/REAPER-2.0/node_modules/chalk/source/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/quinns/REAPER-2.0/node_modules/chalk/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/quinns/REAPER-2.0/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by Simpleboy353** [comment]
How to fix `Error [ERR_REQUIRE_ESM]: require()` for the package chalk ?

- Uninstall the package `chalk`

- Do `npm install chalk@4.1.0`

^^ This should probably fix the error and your bot should start to work normally.

**Comment by finley541** [comment]
Thank you for the help! But.. I now experience this: 

QiMac:REAPER-2.0 quinns$ node .
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:dgram'
Require stack:
- /Users/quinns/REAPER-2.0/node_modules/@discordjs/voice/dist/index.js
- /Users/quinns/REAPER-2.0/node_modules/discord-player/dist/Structures/Queue.js
- /Users/quinns/REAPER-2.0/node_modules/discord-player/dist/Player.js
- /Users/quinns/REAPER-2.0/node_modules/discord-player/dist/index.js
- /Users/quinns/REAPER-2.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/quinns/REAPER-2.0/node_modules/@discordjs/voice/dist/index.js:1:4662)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/quinns/REAPER-2.0/node_modules/@discordjs/voice/dist/index.js',
    '/Users/quinns/REAPER-2.0/node_modules/discord-player/dist/Structures/Queue.js',
    '/Users/quinns/REAPER-2.0/node_modules/discord-player/dist/Player.js',
    '/Users/quinns/REAPER-2.0/node_modules/discord-player/dist/index.js',
    '/Users/quinns/REAPER-2.0/index.js'
  ]
}

**Comment by finley541** [comment]
Thank you but I was wondering after I fixed the chalk issue, it started and I got this: Uncaught Exception: ReferenceError: client is not defined

**Comment by Simpleboy353** [comment]
Issue already open #131
