### ISSUE TITLE
node:events

### ISSUE THREAD

**Issue by brahmendra79** [Simpleboy353/REAPER-2.0#140]
Replit: Package operation failed.
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/aio/node_modules/discord-together/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/aio/node_modules/discord-together/node_modules/discord.js/src/index.js
- /home/runner/aio/node_modules/discord-together/src/DiscordTogether.js
- /home/runner/aio/node_modules/discord-together/index.js
- /home/runner/aio/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/aio/node_modules/discord-together/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by finley541** [comment]
Hey! It seems your Node may be outdated! Please install a new version and this should be fixed!
