### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shayanop** [Simpleboy353/REAPER-2.0#145]
FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> ReferenceError: [CONFIG_ERR] MONGO_DB_CONNECTION_URL_WAS_NOT_FOUND
      at checkValid (C:\Users\lords\OneDrive\Desktop\REAPER-2.0-master\functions\validation\checkValid.js:24:15)
      at Object.<anonymous> (C:\Users\lords\OneDrive\Desktop\REAPER-2.0-master\index.js:69:1)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
      at node:internal/main/run_main_module:17:47
}  reason:  [CONFIG_ERR] MONGO_DB_CONNECTION_URL_WAS_NOT_FOUND
Uncaught Exception: TypeError: Cannot read property 'send' of undefined
C:\Users\lords\OneDrive\Desktop\REAPER-2.0-master\index.js:80
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [exceptionembed] })
                                               ^

TypeError: Cannot read property 'send' of undefined
    at process.<anonymous> (C:\Users\lords\OneDrive\Desktop\REAPER-2.0-master\index.js:80:48)
    at process.emit (node:events:394:28)
    at process._fatalException (node:internal/process/execution:170:25)

**Comment by Simpleboy353** [comment]
You need to add a mongodb connection url to the `config.json` file
