### ISSUE TITLE
Index.js Issue

### ISSUE THREAD

**Issue by Natesplanet** [Simpleboy353/REAPER-2.0#152]
**So my problem is that I get this weird error that I don't know how to fix. Please Help!**
```
 npm start

> reaper-2.0@7.2.0-stable start /home/runner/NBot
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './functions/embeds/Embeds'
Require stack:
- /home/runner/NBot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/NBot/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/NBot/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reaper-2.0@7.2.0-stable start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reaper-2.0@7.2.0-stable start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-13T15_54_23_953Z-debug.log
exit status 1
 
```

**Comment by Natesplanet** [comment]
Can someone please help me?

**Comment by Natesplanet** [comment]
When I do Node Index This happens

` node index
/home/runner/NBot/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/NBot/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 `



Someone please help me I need this bot for my server 🥺 🙏

**Comment by Simpleboy353** [comment]
> When I do Node Index This happens
> 
> ` node index /home/runner/NBot/node_modules/discord.js/src/rest/RESTManager.js:32 const token = this.client.token ?? this.client.accessToken; ^
> 
> SyntaxError: Unexpected token '?' at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object. (/home/runner/NBot/node_modules/discord.js/src/client/BaseClient.js:4:21) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)  `
> 
> Someone please help me I need this bot for my server 🥺 🙏

Your node version seems to be outdated, please install node v16.10.0 (recommended) or higher

**Comment by Natesplanet** [comment]
How do I install that in Replit

**Comment by Natesplanet** [comment]
Ok so I did `npm i node@16.10.0` and I still get this....


When I click Run On Replit (npm start) I get this
` npm start

> reaper-2.0@7.3.0-stable start /home/runner/NBot
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './functions/embeds/Embeds'
Require stack:
- /home/runner/NBot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/NBot/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/NBot/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reaper-2.0@7.3.0-stable start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reaper-2.0@7.3.0-stable start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-20T14_50_36_998Z-debug.log
exit status 1
 `


When I do `node index` 
I get this
` node index
/home/runner/NBot/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/NBot/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 `

**Comment by Natesplanet** [comment]
This is very confusing because it shows 2 different errors in the code which I don't understand.

**Comment by Natesplanet** [comment]
I really need help because this bot is needed in my discord community someone please help 🙏 🥺

**Comment by Natesplanet** [comment]
Going to make a new issue
