### ISSUE TITLE
[FATAL] Possibly Unhandled Rejection

### ISSUE THREAD

**Issue by CrazyGladiator** [Simpleboy353/REAPER-2.0#156]
Bot start fine and in  the middle of a song i get this error.

```
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> DiscordAPIError: Unknown Message
      at RequestHandler.execute (D:\Documents\REAPER-2.0-master\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (D:\Documents\REAPER-2.0-master\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
      at async MessageManager.delete (D:\Documents\REAPER-2.0-master\node_modules\discord.js\src\managers\MessageManager.js:205:5)
      at async Message.delete (D:\Documents\REAPER-2.0-master\node_modules\discord.js\src\structures\Message.js:709:5) {
    method: 'delete',
    path: '/channels/913591399323148288/messages/933772912731770981',
    code: 10008,
    httpStatus: 404,
    requestData: { json: undefined, files: [] }
  }
}  reason:  Unknown Message
Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'send')
D:\Documents\REAPER-2.0-master\index.js:80
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [exceptionembed] })
                                               ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (D:\Documents\REAPER-2.0-master\index.js:80:48)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Comment by CrazyGladiator** [comment]
is there a way i can stop the bot from removing the message ?

**Comment by Simpleboy353** [comment]
Thats a function of the bot to delete the message. So don't worry about this error, it won't affect the performance of the bot.
