### ISSUE TITLE
Can't boot up the bot

### ISSUE THREAD

**Issue by jekabso21** [Simpleboy353/REAPER-2.0#161]
Every time when I try to boot up the bot it shows error. 

 ```
C:\Users\User\Desktop\REAPER-2.0\node_modules\weky\node_modules\discord-buttons\src\v12\Classes\APIMessage.js:8
class sendAPICallback extends dAPIMessage {
                              ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\User\Desktop\REAPER-2.0\node_modules\weky\node_modules\discord-buttons\src\v12\Classes\APIMessage.js:8:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\User\Desktop\REAPER-2.0\node_modules\weky\node_modules\discord-buttons\src\v12\Classes\clickButton.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\User\Desktop\REAPER-2.0\node_modules\weky\node_modules\discord-buttons\src\index.js:53:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

```

**Comment by Simpleboy353** [comment]
If you have installed the package `discord-buttons`, uninstall it and update `weky` to the latest version by doing `npm install weky@latest` in console.
