### ISSUE TITLE
Can someone help?

### ISSUE THREAD

**Issue by Reventium** [Simpleboy353/REAPER-2.0#183]
Error: Cannot find module '/root'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by VeraSmiles** [comment]
Please show the whole console

**Comment by Simpleboy353** [comment]
Try updating to the latest version
