### ISSUE TITLE
Issue starting up bot | Syntax Error: Invalid or unexpected token

### ISSUE THREAD

**Issue by Harrsn** [Simpleboy353/REAPER-2.0#185]
Not entirely sure what to do here, any advice would be greatly appreciated!
The highlighted sections are:
```
SyntaxError: Invalid or unexpected token
    at loadCommands (C:\Users\harrs\Desktop\t\handler\loadCommands.js:13:23)
    at Object.<anonymous> (C:\Users\harrs\Desktop\t\index.js:52:1)
```
Full error:
```
SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadCommands (C:\Users\harrs\Desktop\t\handler\loadCommands.js:13:23)
    at Object.<anonymous> (C:\Users\harrs\Desktop\t\index.js:52:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by Simpleboy353** [comment]
Can you please make sure that the `loadCommands` file has no syntax issues (like missing "{")

**Comment by VeraSmiles** [comment]
have you filled in the bot token in config.json?

**Comment by Simpleboy353** [comment]
No response and try updating to the latest version
