### ISSUE TITLE
Issue on Replit

### ISSUE THREAD

**Issue by Nateay0** [Simpleboy353/REAPER-2.0#199]
Could someone help me fix this issue please!!

```
 npm start

> reaper-2.0@8.0.0 start /home/runner/NBot
> node index.js

.-----------------------------.
|   Commands    | Load Status |
|---------------|-------------|
| awkword.js    | ✔️          |
| betrayal.js   | ✔️          |
| chess.js      | ✔️          |
| doodlecrew.js | ✔️          |
| fishington.js | ✔️          |
| lettertile.js | ✔️          |
| poker.js      | ✔️          |
| spellcast.js  | ✔️          |
| youtube.js    | ✔️          |
'-----------------------------'
.-------------------------------.
|    Commands     | Load Status |
|-----------------|-------------|
| awkword.js      | ✔️          |
| betrayal.js     | ✔️          |
| chess.js        | ✔️          |
| doodlecrew.js   | ✔️          |
| fishington.js   | ✔️          |
| lettertile.js   | ✔️          |
| poker.js        | ✔️          |
| spellcast.js    | ✔️          |
| youtube.js      | ✔️          |
| antilink.js     | ✔️          |
| antiwords.js    | ✔️          |
| autorole.js     | ✔️          |
| dashboard.js    | ✔️          |
| joinchannel.js  | ✔️          |
| joinmessage.js  | ✔️          |
| leavechannel.js | ✔️          |
| leavemessage.js | ✔️          |
| prefix.js       | ✔️          |
'-------------------------------'
/home/runner/NBot/Commands/Fun/fact.js:9
      "Though less common than earthquakes, the moon actually has moonquakes, too. That's right. Moonquakes. Pretty much everyone is interested in space, so this is always a good fact to pull out.","
                                                                                                                                                                                                      ^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadCommands (/home/runner/NBot/handler/loadCommands.js:13:23)
    at Object.<anonymous> (/home/runner/NBot/index.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

**Comment by Nateay0** [comment]
I went through where the file has an issue and it seems have a error but I could not figure out how to fix it.

![image](https://user-images.githubusercontent.com/92893096/186280069-154f5ac0-d6fe-4fb7-9143-8a7d55d7c75c.png)

**Comment by Nateay0** [comment]
I found the issue. Some people put quotes in the question and the system thought that was with the code so the quotes had to be removed. I will also add a pull request for it.
