### ISSUE TITLE
ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by ryanalieh** [Simpleboy353/REAPER-2.0#211]
PS C:\Users\ryanl\REAPER-2.0> node index
C:\Users\ryanl\REAPER-2.0\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The module '\\?\C:\Users\ryanl\REAPER-2.0\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (C:\Users\ryanl\REAPER-2.0\node_modules\bindings\bindings.js:112:48)
    at new Database (C:\Users\ryanl\REAPER-2.0\node_modules\better-sqlite3\lib\database.js:48:64)
    at new Enmap (C:\Users\ryanl\REAPER-2.0\node_modules\enmap\src\index.js:169:11)
    at Object.<anonymous> (C:\Users\ryanl\REAPER-2.0\index.js:50:13)
    at Module._compile (node:internal/modules/cjs/loader:1119:14) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.9.0

**Comment by Simpleboy353** [comment]
Delete the `node_modules` folder and the `package-lock.json` file. Then do `npm install` amd install all the required packages again. This should fix the error.

**Comment by BTNGaming** [comment]
So I've tried this and tested it, the issue always ends up being better-sqlite3. I've tried everything I could think of to resolve this to no avail. Any other solutions?

**Comment by Simpleboy353** [comment]
delete the `package-lock.json` file and the `node_modules` folder. After deleting, re-install all the required packages. This should fix this error.

**Comment by BTNGaming** [comment]
Yeah, I've attempted that as well. I did this on 2 machines, windows 10 and a centos system I have. I have had no luck though still.

**Comment by BTNGaming** [comment]
If easier you can reach me on discord @ BTNGaming#7728

I can run you through everything i've tried and maybe we can find a final solution to resolve this for everyone?

**Comment by BTNGaming** [comment]
https://i.imgur.com/t4BgMeF.png
https://i.imgur.com/KtEnb5L.png

**Comment by Simpleboy353** [comment]
Hey there! I know I am replying very late... but I am working on a new update for the bot, which will most likely fix your errors... Hope this helps!
