### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by InsufiKoder** [Simpleboy353/REAPER-2.0#41]
uhh so i get this error when i try to run the bot

C:\Users\Administrator\Desktop\Bot\Commands\Info\help.js:70
<<<<<<< Updated upstream
  ^^

SyntaxError: Unexpected token '<<'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at loadCommands (C:\Users\Administrator\Desktop\Beta\handler\loadCommands.js:13:23)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Beta\index.js:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

**Comment by Simpleboy353** [comment]
You are using an older version of this repository. Please update to the latest version if this repository.

**Comment by InsufiKoder** [comment]
> You are using an older version of this repository. Please update to the latest version of this repository.

I see. Thanks for help

**Comment by Bozo9** [comment]
Hey umm how do i get the new update or update the current one?

**Comment by Simpleboy353** [comment]
> Hey umm how do i get the new update or update the current one?

In your fork repository, you will have an option: *Fetch Upstream*. Use this to fetch all the new changes from REAPER-2.0 repo to your Forked Repo.

**Comment by Bozo9** [comment]
> > Hey umm how do i get the new update or update the current one?
> 
> In your fork repository, you will have an option: _Fetch Upstream_. Use this to fetch all the new changes from REAPER-2.0 repo to your Forked Repo.

Ooo alright, makes sense.
