### ISSUE TITLE
the game commands dont work with v12.5.3 maybe package err : discord-gamecore

### ISSUE THREAD

**Issue by HACKERPROTM** [Simpleboy353/REAPER-2.0#56]
(node:4) UnhandledPromiseRejectionWarning: TypeError: INVALID_MENU_TYPE: Invalid type
2021-09-09T21:47:41.400601+00:00 app[Worker.1]:     at Object.resolveMenu (/app/node_modules/discord-buttons/src/v12/Util.js:53:64)
2021-09-09T21:47:41.400602+00:00 app[Worker.1]:     at /app/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:235:118
2021-09-09T21:47:41.400603+00:00 app[Worker.1]:     at Array.map (<anonymous>)
2021-09-09T21:47:41.400603+00:00 app[Worker.1]:     at /app/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:234:33
2021-09-09T21:47:41.400603+00:00 app[Worker.1]:     at Array.map (<anonymous>)
2021-09-09T21:47:41.400604+00:00 app[Worker.1]:     at APIMessage.resolveData (/app/node_modules/discord-buttons/src/v12/Classes/APIMessage.js:230:40)
2021-09-09T21:47:41.400604+00:00 app[Worker.1]:     at ExtendedTextChannel.send (/app/node_modules/discord-buttons/src/v12/Classes/TextChannel.js:19:62)
2021-09-09T21:47:41.400605+00:00 app[Worker.1]:     at SnakeGame.startGame (/app/node_modules/discord-gamecord/src/Snake.js:161:48)
2021-09-09T21:47:41.400605+00:00 app[Worker.1]:     at Object.execute (/app/commands/Games/snake.js:27:12)
2021-09-09T21:47:41.400606+00:00 app[Worker.1]:     at commandExecute (/app/events/guild/message.js:351:28)
2021-09-09T21:47:41.400606+00:00 app[Worker.1]:     at /app/events/guild/message.js:395:11
2021-09-09T21:47:41.400607+00:00 app[Worker.1]:     at /app/node_modules/mongoose/lib/model.js:5074:18
2021-09-09T21:47:41.400607+00:00 app[Worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-09-09T21:47:41.400607+00:00 app[Worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-09-09T21:47:41.400618+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-09-09T21:47:41.400661+00:00 app[Worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HACKERPROTM** [comment]
no worrys found err

**Comment by HACKERPROTM** [comment]
i just went inside node_modules and changed its functions
