### ISSUE TITLE
error

### ISSUE THREAD

**Issue by socktow** [Simpleboy353/REAPER-2.0#68]
[FATAL] Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
      at WebSocketManager.createShards (D:\moderation\REAPER-2.0\node_modules\discord.js\src\client\websocket\WebSocketManager.js:249:15)
      at async Client.login (D:\moderation\REAPER-2.0\node_modules\discord.js\src\client\Client.js:245:7) {
    [Symbol(code)]: 'DISALLOWED_INTENTS'
  }
}  reason:  Privileged intent provided is not enabled or whitelisted.
Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'send')
D:\moderation\REAPER-2.0\index.js:79
  client.channels.cache.get(ERROR_LOGS_CHANNEL).send({ embeds: [exceptionembed] })
                                               ^

TypeError: Cannot read properties of undefined (reading 'send')
    at process.<anonymous> (D:\moderation\REAPER-2.0\index.js:79:48)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:170:25)

**Comment by Simpleboy353** [comment]
You are using the intents which are not whitelisted for your bot, try removing that intent from the index.js file
